build.gradle: update JUnit 5 dependency
Eclipse 20.03 requires an updated version of Junit 5, or tests will fail
to run with this error:

    java.lang.NoClassDefFoundError: org/junit/platform/commons/PreconditionViolationException